<?php include('header.php') ?>


<div class="headImage">

   <div class="heading">
      Instruments
   </div>
</div>
<div class="page">
   <div class="blog-page">



      Now we are towards the end of our blogs on the heart of robotics. In this blog you are going to learn about
      various instruments which you are going to use to make your little robots ready for a fight in the arena.
      <br />
      <img src="./img/images/Instruments/image5.gif" class="img-responsive floating-image center">
      <br />
      Let's start with how to make joints.
      <br />
      <img src="./img/images/Instruments/image9.gif" class="img-responsive floating-image center">
      <br />
      In electronics, joints are made with the help of a process called soldering. Let’s dive to make joints, soldering
      joints 😏.
      <div class="blogPageHeading">Soldering</div>

      <br />Rome was not built in a day and so weren’t our exciting robots which crushed every competitor in every
      competition they participated in. The controlling unit of our robots consists of various electronic components and
      combining them magically requires an elder wand and a magical fuel which is known as “Soldering Iron” and “solder”
      respectively in the Geek circle.
      <br /><img src="./img/images/Instruments/image24.gif" class="img-responsive floating-image right"> <br />Various
      components have to be joined via a conductive link and in our case, the solder does the job, it is a highly
      conductive material with a low melting point.
      <br />The process in which two or more items are joined together (electronic components and boards) by melting and
      putting a filler metal also known as solder into the joint, the filler metal having a lower melting point than the
      adjoining metal i.e terminals of component or Circuit board is called Soldering.
      <br /><br />Ok, moving to what soldering iron is and what it can do?<br /><br />
      <div class="blogPageSubHeading">Soldering iron</div>
      <br />
      <img src="./img/images/Instruments/image10.jpg" class="img-responsive floating-image right"> <br />
      A soldering iron is a hand tool used in soldering. It supplies heat to melt solder so that it can flow into the
      joint between two workpieces. A soldering iron is composed of a heated metal tip and an insulated handle. Heating
      is often achieved electrically, by passing an electric current (supplied through an electrical cord or battery
      cables) through a resistive heating element.
      <br /><br />There are other types of solder irons available in the market rather than a simple one :<br /><br />
      <img src="./img/images/Instruments/image4.png" class="img-responsive floating-image center">
      <div style="text-align:center">Cordless solder iron </div>
      <img src="./img/images/Instruments/image22.png" class="img-responsive floating-image center">
      <div style="text-align:center">Variable temperature solder iron</div>
      <br /><br />
      <div class="blogPageSubHeading">Solder</div>
      <br /><img src="./img/images/Instruments/image18.png" class="img-responsive floating-image right">
      Solder is a conductive alloy substance with a low melting point, used in the electronics industry to electrically
      connect components together. It is frequently used to join wires to leads of components such as switches or to
      join components of all kinds to a circuit board or two pieces of metals etc.
      For regular electronic purposes, wire made of solder which is usually an alloy of tin and lead is used for
      soldering. This wire is melted with the help of soldering iron and fuses with the metal that is needed to be
      joined. It is necessary to avoid the fumes generated by soldering as they contain residue of lead which is
      harmful.
      <br /> <br><br><br>
      <div class="blogPageSubHeading">Flux</div>
      <img src="./img/images/Instruments/image7.jpg" class="img-responsive floating-image center" width="400px" height="400px">
      <br />
      Sometimes, the metal contacts which we wanted to solder don't get soldered properly even if we follow all steps
      correctly. The reason behind it is the oxides formed on the metal surface due to the reaction with compounds in
      air which prevents the fusion of solder and the metal surface. To get rid of this layer of oxide, flux is used. It
      is usually in paste form at room temperature. It removes the layer of oxide and creates a clean site of pure metal
      ready to get fused with solder to make a perfect joint. Flux also leaves the residue of impurity on the board
      which needs to be cleaned with isopropyl alcohol if your flux is water insoluble or water if your flux is water
      soluble . To get a clean site of metal whose surface is oxidized, flux paste is applied and little heat with the
      solder iron is provided for flux to work on the site.

      <img src="./img/images/Instruments/image16.gif" class="img-responsive floating-image center">
      <img src="./img/images/Instruments/image2.gif" class="img-responsive floating-image center">

      <br />
      <br />Above is the gif showing soldering on an oxidized metal surface (top) and soldering on the same surface
      after applying flux (bottom).
      <img src="./img/images/Instruments/image12.png" class="img-responsive floating-image right"><br /><br />
      Solder wires available these days already have flux at their core to ease the work of soldering. Flux
      automatically cleans the area while using such solder wire making sites prepared for soldering.
      <br />External flux paste of rosin and liquid flux is also available in the market.

      <br /><br /><br /><br />


      If you’re wondering how to solder components like professionals, <a
         href="https://www.youtube.com/watch?v=6rmErwU5E-k">this video will help you.</a>
      <br />
      <img src="./img/images/Instruments/image13.png" class="img-responsive floating-image center"><br />
      <br />
      <div class="blogPageHeading">Circuit Boards</div>
      <br />
      To make our circuits more robust, portable and convenient, with ease of making. We require a base. Circuit boards
      are the base for circuits, a board on which we design our circuits. They are categorized in three types are as
      follows:
      </br> <img src="./img/images/Instruments/image19.png" class="img-responsive floating-image left">
      </br></br>
      <div class="blogPageSubHeading">Breadboard</div><br />

      Unlike the ones we would be making, we aren’t robots so we’re susceptible to make mistakes. Taking all the
      components we “think” we require and straightaway soldering them according to the way we “presume” could be a
      risky affair, and making mistakes at that stage would result in sacrificing several important and sometimes
      valuable components, so we tend to make a prototype and test our circuit design and functioning before permanently
      soldering them together. To make such prototypes, we tend to use a breadboard.
      <br />A breadboard refers to a solder-free, plug-and-play platform allowing for speedy insertion and removal of
      electrical components in circuit-building applications. The breadboard has strips of metal underneath the board
      and connects the holes on the top of the board. The metal strips are laid out as shown below. Note that the top
      and bottom rows of holes are connected horizontally and split in the middle while the remaining holes are
      connected vertically.
      </br> <img src="./img/images/Instruments/image3.png" class="img-responsive floating-image left">
      <img src="./img/images/Instruments/image11.png" class="img-responsive floating-image right">
      </br></br></br>
      <div></div>
      <img src="./img/images/Instruments/image17.png" class="img-responsive floating-image center">
      <br /> This is how an IC is used on a breadboard. And above mentioned are the internal connections of a
      breadboard. The colored lines show the connected pins of the breadboard. As a convention, pins on the right of the
      red line are used for positive terminals and pins at the left of blue line are used for negative terminals.
      Vertical lines are called power rails due to this reason and horizontal lines are called component rails as
      electrical and electronic components are used on thes rails/lines.
      <br />But can you figure out why there is a channel in the middle of the breadboard. Think!<br /><br />
      <img src="./img/images/Instruments/image20.jpg" class="img-responsive floating-image right"
         style="height:300px; width:300px;">
      <div class="blogPageSubHeading">Stripboard</div>
      <br />Stripboard is one of the commonly-used types of prototyping boards. These boards are intended for
      permanently assembling one-off circuits, especially prototypes. The board is made from an insulating material,
      usually a resin-bonded plastic or fiberglass. One side has parallel copper strips on it, spaced 2.54 mm apart.
      There are holes bored in these strips, also 2.54 mm apart. Components are placed on the other side of the board
      with their wires bent to pass through the holes. The wires are soldered to the copper strips, the projecting ends
      being cut off to make the assembly neater. Only the shiny part with copper plated strips can get soldered, the
      other side with no copper plating cannot be soldered so components must be inserted and soldered with care.
      <img src="./img/images/Instruments/image21.png" class="img-responsive floating-image left"><br />The strips correspond
      to the rows of sockets on breadboards, allowing several components to be joined together, but a strip has many
      more than five holes so numerous connections are possible. Using a special tool, strips can be cut into shorter
      lengths where it is necessary to use one strip for making several different connections. A circuit built on a
      stripboard has permanently soldered connections, but it is not difficult to remove a component and solder in one
      of a different value, or even to completely modify part of the circuit. A prototype circuit may be built and
      tested stage by stage.
      <br /><br /><br />
      <img src="./img/images/Instruments/image8.png" class="img-responsive floating-image right"
         style="height:200px; width:300px;">

      <div class="blogPageSubHeading">PCB</div><br />
      You must have encountered some green, red or blue colored boards inside electronic devices having shiny lines with
      components on them. These are the highly robust and portable circuit boards. They are PCBs or printed circuit
      boards.
      It is a board that has lines and pads that connect various points together. In the picture, there are traces that
      electrically connect the various connectors and components to each other.
      <img src="./img/images/Instruments/image23.png" class="img-responsive floating-image left"> It allows signals and
      power to be routed between physical devices. Solder makes the electrical connections between the surface of the
      PCB and the electronic components. Being metal, solder also serves as a strong mechanical adhesive. A PCB is
      printed with the help of a printing machine but the PCBs are first designed in CAD softwares like EAGLE, KiCAD,
      etc. and then these software aid the printing of PCBs.

      <br /> <br />PCB is composed of four layers usually stacked on one another as shown in left. <br />
      <br /># Substrate is the very base of PCB that provides strength to the PCB and support to its components. It is
      usually made of fiberglass.
      <br /># A layer of copper is fabricated above the substrate of PCB which makes the conductive electrical paths of
      circuit boards. Some boards with dual side circuitry have both sides fabricated with copper layers so that
      components can be soldered on both sides.
      <br /># A solder mask is applied above the copper layer so as to prevent it from shorting from external metals and
      also it acts as a protective mask for copper from being damaged physically and chemically making the circuit path
      undisturbed.
      <br /># A white layer of silk screen is used to print visuals on the circuit board above the solder mask which
      helps the manufacturer or designer to share info about component values or placement directly via board.
      <br /><br />So, these are the basics regarding PCBs. You’ll again encounter PCBs in near future but till then,
      let’s just measure the components we soldered on our board are of correct values or not coz one of the resistors
      lost its color code. How to measure? No worries! Just go further in the blog.
      <br /><br />
      <div class="blogPageHeading">Multimeter</div>
      <br />A multimeter is an electronic measuring device. It typically measures Voltage, Current, and Resistance. Two
      types of multimeters available in the market are- Analog and Digital.
      <br /> <img src="./img/images/Instruments/image14.jpg" class="img-responsive floating-image left"
         style="height:400px; width:440px;">
      <img src="./img/images/Instruments/image6.gif" class="img-responsive floating-image left"
         style="height:400px; width:440px;">
      </br><br />
      <br />The most common and cheap multimeter you can get is the Haoyue DT830D. It can measure -
      <img src="./img/images/Instruments/image15.png" class="img-responsive floating-image right"
         style="height:300px; width:340px;"> </br>
      <br /># AC/DC voltage
      <br /># DC current
      <br /># Resistance value
      <br /># Frequency of square wave
      <br /># hFE or forward current gain of transistor
      <br /># Continuity of a circuit
      <br /># Temperature (some other version of it can measure)
      <br /><br /> What are the components of a multimeter?
      <br /><br /> Here they are-
      <img src="./img/images/Instruments/image1.png" class="img-responsive floating-image center">
      <br /><br /> >> Two wire probes with different colors are provided to aid in work, they can be inserted easily in
      jacks provided shown above.<br />
      <br /># 10A jack is internally connected to a 10A max fuse and only measures utmost 10A for max 10 seconds. From
      convention, the red probe is connected to this jack as it signifies high potential.
      <br /># VΩmA jack has a fuse that allows max 200mA max, 600V AC/DC max. From convention, a red probe is used with
      this jack.
      <br /># COM is the ground jack and black probe is used with it from convention.
      <br /># hFE measuring jack is used to measure forward current gain of transistor. How? Follow <a
         href="https://www.petervis.com/electronics%20guides/DT830B/DT830B%20Transistor%20Test.html">this</a> link.
      <br /><br />>> Function switch is a knob which is used to set the mode for the component whose measurement or
      testing we need. The arrow indicates the mode on which the multimeter is at.
      <br />>> LCD is used to display the info about the component.
      <br />>> These multimeters use batteries for their functioning but some versions support charging of these
      batteries.
      <br /><br />How and where to use a multimeter?
      <br />Follow this tutorial<a href="https://www.youtube.com/watch?v=SLkPtmnglOI"> here</a> and get an insight of
      how to use it. But-


      <br />
      <table style="border: 2px solid black; padding:5px;">
         <tr>
            <td style="padding:10px;">
               What will happen if I set my multimeter to check continuity and connect the probes to each end of a
               resistor of 6.3Ω and a resistor of 29Ω? Will it beep for both resistors or not? And why? Do some
               research.
            </td>
         </tr>

      </table>

      <br />Time to wrap this up now guys.
      <br />I think we have our first stone of robotics “BEE Stone”...or not?🤔 Now it’s time to get “Soul(Algorithm) stone”. In the
      next few blogs, we will study the body of robotics, so be with us on the journey to collect all stones of
      robotics.



<br><br><br>
<table style="border: 2px solid black;">
         <tr>
            <td>
               Mail your assignment answers to <a href="mailto:puneet@zine.co.in">puneet@zine.co.in</a> and contact us in communication channel with doubts.
            </td>
         </tr>
      </table>
<br><br><br>
<ul class="pager">
  <li class="previous"><a href="./batteries.php">Previous</a></li>
</ul>




   </div>
</div>

<?php include('footer-1.php') ?>