<?php include('header.php') ?>


<div class="headAlgoImage">
</div>
<div class="heading">
Introduction to Aeromodelling.
</div>

<div class="page">
    <div class="blog-page">
        <br><br>

       

If you have ever wondered how someone could fly, what would you think of? Wings? Propellers? [Because that’s how the Wright brothers did it, duh]. But how does it work? We are here to answer that question for you. That’s what we do in aeromodelling, we design, construct and fly our airplanes. So it can be described as the art of designing, building and flying miniaturized aircrafts (Be it powered or unpowered). So, kudos to you, you have been an aeromodeller since your childhood.
<br><br>
But the real question is why do we need to study this field, don’t we already have the best of aircrafts?
<br>Aero-modelling has an increasing area of scope for the last decades. Aero-modeling may be utilized in many ways. Aero-modeling is a hobby as well as a profession.
<br><br>
Some applications and future opportunities of Aero-modeling are:-
<br>·        For hobby. Have large demand in various hobby shops, children toys etc.
<br>·        For surveillance, various aero-models have been fabricated and improvements are going on in this field.
<br>·        Subject of research, design and development.
<br><br>
Let's start with Newton's Laws of Motion, “An object shall stay at rest unless acted upon by an external force”. We are all familiar with this law. 
So, that means we need an upward force to lift an object, Right? <br>
Let's just use a crane and lift the said person then. 


<img src="../img/images/aero/image51.jpg" class="img-responsive floating-image right">

But that’s not flying… 
<br><br>
So, we want the person to have a local force generation, which he can control to decide how he moves. Let’s call this required force Lift. 
So, how would you propose to lift yourself up
Looks at Doraemon with intent, Bamboo-copter? 
<br><br>                                                   
You are close, but not exactly the right equipment for the job. So how about a Plane? Exactly! We will talk about this in detail later. 
Even birds produce lift using wings. (Birds are the <a href="https://www.oneindia.com/2006/10/15/the-birds-story-and-a-rocket-scientist-1160921813.html">reason</a>
 APJ Abdul Kalam chose to be an aeronautical engineer!) Let’s dive in and find out how. 
<br><br>

<div class="blogPageHeading">Revisiting Newton’s Laws of Motion</div>
<br>
Jumping to basic physics, Newton’s third law of motion suggests, for every force exerted on an object as an action, there is a force experienced called as a reaction. So for generating lift, the air is to be pushed down by wings(action), so that an equal upward force is generated(reaction).
<br><br>
Now, we need a medium to work in, yes the air around us. Objectively, a fluid is any substance that flows, and thus air is also a fluid, and thus also follows fluid principles. The air behaves like a fluid with its own set of properties which we can harness to complete our goal of flight. It is because of this fluid we can travel across distances which were unimaginable before.
<br><br>
One of the properties of the fluid is the resistance to motion offered by the fluid when a solid body moves through it. This resistive force is called Drag force.
<br><br>
Drag is generated by the difference in velocity between the solid object and the fluid. If there is no motion, there is no drag. It makes no difference whether the object moves through a static fluid or whether the fluid moves past a static solid object. 
<br><br>
So for our person to fly we need to counter 2 forces, Weight and Drag. Weight is countered using the Lift force generated by the person’s flying equipment. The Drag force is countering the thrust which moves the aircraft forward. These 4 four forces are the main aerodynamic forces acting on the craft. In the state of equilibrium flight, the thrust force equals the drag force, and the lift is equal to the weight.
<br>
<img src="../img/images/aero/image26.jpg" class="img-responsive floating-image center">
<br>
Lift and drag are aerodynamic forces that depend on the shape and size of the aircraft, air conditions, and the flight velocity. Lift is directed perpendicular to the flight path and drag is directed along the flight path.
<br><br>As lift and drag, both are aerodynamic forces, their ratio is important to the aerodynamic efficiency. Their ratio is called the L/D ratio. An aeroplane has a high L/D ratio if lift generation is high compared to the drag. Now, for cruise conditions, which is the most efficient phase of an aeroplane, the lift should be equal to the weight and thrust equal to drag. An aircraft with a high L/D ratio can carry a large payload, for a long time, over a long distance. Similarly, thrust to weight ratio is important to aircraft propulsion [propulsion means to push forward], (F/W) ratio is directly proportional to the acceleration of the aircraft.
<br><br>
<div class="blogPageHeading">Aerofoil and Bernoulli’s Equation</div>
<br>
You might have already learnt about Bernoulli's equation in secondary school, and no, the only usage is not in solving complex equations of a competitive exam, like IIT-JEE (nostalgia weared-off yet?) but it has some practical applications as well.
<br><br>
The curvature of aerofoils [An aerofoil is the cross-sectional shape of a wing, blade, or sail. An airfoil-shaped body moving through a fluid produces an aerodynamic force.] when moving through the air, ensures that there are two streamlines, one above the surface, and one below it.
<br>The path length of both streamlines are different, the ambient wind coming in has to travel different distances. Now there are two concepts which you must be learning right from your school.
<br><br>
<b>1. Mass Conservation</b>, (yup, the very basic law, stating the mass always remains conserved, be it in chemistry or physics)
<br><b>2. Bernoulli’s Equation</b> (assuming incompressible flows right now)
<br><br>
<img src="../img/images/aero/image48.png" class="img-responsive floating-image center">
<br>
<img src="../img/images/aero/image58.png" class="img-responsive floating-image center">
<br>
Now because the mass should be conserved, the number of air particles passing through the surface of the wing from the starting of streamlines should be equal to air particles leaving, and because both path distances are different, the air particles above the wings travel with more velocity than below the wings (higher velocity accommodates less pressure, from Bernoulli’s principle), the pressure above the wings should be less and higher below the wings.
Thereby generating the lift.
<br><br>
<div class="blogPageHeading">Angle of attack</div>
<br>
The angle of attack is the angle between the aerofoil’s chord (taken as reference line) and the airspeed vector. When an aeroplane takes off, the pilot applies throttle to make the aeroplane taxi along the runway. But just before lifting off, the pilot pulls the aircraft up. The nose of the aircraft rises, increasing the angle of attack and producing the lift needed for takeoff. For thin airfoils, the lift is directly proportional to the angle of attack for small angles.  What would happen if the angle of attack is more than this range? The air particles kind of “stick” to the surface, creating a layer near the surface, thereby changing the shape. When this layer separates, the effective shape is much different than the physical shape, the wing is disturbed, and this condition is called stalling.
<br>
<img src="../img/images/aero/image38.jpg" class="img-responsive floating-image center">
<br>
Follow this <a href="https://youtu.be/ZuGPcvC4vbw">video</a> for an illustration of stalling.
<br>Here is a question for you, for a particular airfoil, how is angle of attack related to lift and drag forces?
<br><br>
<b>Assignment:</b> You might have seen people doing stunts with planes, making them fly inverted. How does this happen? Explain the physics behind it.
<br><br>
<div class="blogPageHeading">Types of Aerofoils</div>
<br>
<img src="../img/images/aero/image52.png" class="img-responsive floating-image center">
<br><br>
<div class="blogPageSubHeading">1. Symmetrical</div>

<br>
<img src="../img/images/aero/image31.png" class="img-responsive floating-image center">
<br>a)Such aircraft ensures low drag.
<br>b)It is good for precision aerobatics.
<br>c)Good for high speed.
<br><br>
<div class="blogPageSubHeading">2. Semi-symmetrical</div>


<br>
<img src="../img/images/aero/image53.png" class="img-responsive floating-image center">

<br>a)Good for aerobatics.
<br>b)Good for gliding.
<br>c)Wider speed ranges.

<br><br>
<div class="blogPageSubHeading">3.  Flat-Bottomed</div>

<br>
<img src="../img/images/aero/image16.png" class="img-responsive floating-image center">	

<br>a)True flat-bottom airfoils are a poor choice for any design.  
<br>b)They are extremely speed-sensitive. (Therefore, nearly impossible to trim.)
<br>c)Used for powered aircraft (Compromise aerodynamic shape for speed)
<br>d)They do not penetrate the air well but can stay aloft at very low speeds.
<br><br>
    <div class="blogPageSubHeading">4. Under cambered</div>

    <br>
<img src="../img/images/aero/image49.png" class="img-responsive floating-image center">	

    <br>a)Maximum lift.
    <br>b)Low stall speed.
<br><br>
<div class="blogPageHeading"> Types of Wings</div>
<br>
How are these helpful, you ask? Well, different planes have different wings for different purposes. Some planes have wings to carry heavy planes over long distances. Some are designed to fly at very fast speeds, or at very high altitudes. Some are designed to have high maneuverability. Also remember that the lift to drag ratio that we talked about earlier? Well, it turns out that the wing parameters are really important for the L/D Ratio and aerodynamic efficiency.
<br><br>    
Let’s take a look at some wing types.
<br><br>

<div class="blogPageSubHeading">Rectangular Wings</div>
<img src="../img/images/aero/image22.png" class="img-responsive floating-image center">	
<br>* Rectangular planform. 
<br>* This design is easy to manufacture, but has low aerodynamic efficiency.
<br><br>
<div class="blogPageSubHeading">Elliptical Wings</div>
<img src="../img/images/aero/image3.png" class="img-responsive floating-image center">	
<br>* Elliptical planform, its leading and trailing edge approximates two segments of ellipse.
<br>* Difficult to manufacture.
<br><br>
<div class="blogPageSubHeading">Tapered Wings</div>
<img src="../img/images/aero/image57.png" class="img-responsive floating-image center">	
<br>* Along the span, the length of chord varies, giving an approximate elliptical planform.
<br>* Isn’t as efficient as Elliptical, but it is bit easy to manufacture compared to Elliptical wings

<br><br>


<div class="blogPageSubHeading">Aircraft can also be classified by their speed:</div>
To classify them. We must first understand some basic terminology.
<br>
<img src="../img/images/aero/image1.png" class="img-responsive floating-image center">	
<br>
Types of Aircraft:
<br><br>
<div class="blogPageSubHeading">Subsonic:</div>  
<br>	
Mach number  < 1.
<img src="../img/images/aero/image2.png" class="img-responsive floating-image center">
<br><br>
<div class="blogPageSubHeading">Trans-sonic:</div> 
<br>
0.8 < Mach number < 1.2
<img src="../img/images/aero/image28.jpg" class="img-responsive floating-image center">	
<br><br>
<div class="blogPageSubHeading">Supersonic:</div>
<br>
 1.2 < Mach number < 5
 <img src="../img/images/aero/image19.png" class="img-responsive floating-image center">	
 <br><br>
<div class="blogPageSubHeading">Hypersonic:</div> 
<br>
5 < Mach number
(Disclaimer: Just a concept, not yet made)
<img src="../img/images/aero/image47.png" class="img-responsive floating-image center">	









        <br><br><br>

        <ul class="pager">
            <li class="next"><a href="./memory.php">Next</a></li>
        </ul>



    </div>
</div>

<?php include('footer-1.php') ?>
