<?php include('header.php') ?>


<div class="headAlgoImage">
</div>
<div class="heading">
    Multirotor Aircraft
</div>



<div class="page">
    <div class="blog-page"><br>
    A multirotor is a rotor based aircraft with 2 or more lift generating rotors. The advantage that comes with a multi rotor (with fixed pitch blades i.e. angle of attack of the blade is constant), is the simple rotor mechanics needed for flight control and ability to hover and operate in confined areas. 
<br>
<img src="../img/images/aero/image17.png" class="img-responsive floating-image left" width="400">
        <img src="../img/images/aero/image46.png" class="img-responsive floating-image right" width="400">
<br>
<img src="../img/images/aero/image20.gif" class="img-responsive floating-image center">
<center>This is a multicopter system designed for agricultural use.
</center>

<br><br>
The construction and control is easy for multirotors and are often used in remotely controlled drones, and aerial vehicle projects, and are easily configurable to equip more weight carrying capacity or thrust to weight ratio. Another use case for multi rotors is aerial mapping and inspection systems, their hovering ability allows it to be very useful in such cases. 
<br> But they are not exactly all good either: Cons. Because of the multi rotor setup the flight times for the craft are rather short as the battery drains faster. As compared to a fixed wing aircraft the payload capacity is also smaller.
<br><br>
As we know Quadcopters make use of 4 Motors. So, Two of these motors spin clockwise while the other two spin counterclockwise. Motors on the same axis spin in the same direction, as illustrated here. <b>Altitude</b> is a term that you’re probably familiar with – it simply describes going up or down. A quadcopter can either hover or adjust its altitude by applying equal thrust to all four rotors.
 <br><br>
 <img src="../img/images/aero/image4.png" class="img-responsive floating-image left" width="450px">
 <img src="../img/images/aero/image30.png" class="img-responsive floating-image right" width="450px">

To adjust its <b>Yaw</b>, or make it turn left or right, the quadcopter applies more thrust to one set of motors [image on the right]. For example, a quadcopter may apply more thrust to the two motors that spin clockwise to make a turn. This happens because the Angular momentum generated by the propellers provides a torque to the body of the quadcopter. The torque is cancelled out when all motors run at the same speeds. 
<img src="../img/images/aero/image4.png" class="img-responsive floating-image left">

<b>Pitch and roll</b>  on the other hand are adjusted by applying more thrust on one rotor and less to the other opposing rotor. For example, the quadcopter can adjust its pitch by applying more thrust to the clockwise spinning motor in the front and less thrust to the clockwise spinning motor directly opposite in the back.
<br> One thing that makes quadcopters easy to fly is that you don’t actually have to adjust the motor speeds manually as this is where the controller and electronics come in. The mechanics of flight of a quadcopter make it agile as compared to a fixed-wing aircraft. This allows doing manoeuvres which are not possible in any other form of flight, Zine Drone Racing explores these avenues. 
 <br>
 So, how is it made? <br>
Let's look at the construction in depth:

<br><br><br>
<img src="../img/images/aero/image44.png" class="img-responsive floating-image center">
<img src="../img/images/aero/image11.gif" class="img-responsive floating-image center">
<img src="../img/images/aero/image34.jpg" class="img-responsive floating-image center">
<br><br>

<b>Frame: </b> 
<br>
<img src="../img/images/aero/image25.jpg" class="img-responsive floating-image center">

Think of the frame for a drone as a chassis is for a car. The frame is the integral part of the multirotor as it holds all components, so it's necessary for it to be sturdy and rigid. The frame structure varies depending on the multirotor configuration, in the picture above you see a quadcopter’s X frame. Generally it's preferred to have a light and strong frame, so materials like fibre and plastics are used often. Learn <a href="https://www.getfpv.com/learn/new-to-fpv/all-about-multirotor-fpv-drone-frame/">more</a>.
       <br>
       <br>

<b> Motor & propellers: </b>
<br>
<img src="../img/images/aero/image13.png" class="img-responsive floating-image left" width="450px">
<img src="../img/images/aero/image39.png" class="img-responsive floating-image right" width="450px">
<br>
<br><br>
Well if the car needs wheels, similarly, a multirotor needs propellers. The wheels are run by the engine in a car, and propellers are run by the motor for a multirotor.  
<br> When looking for a motor, you will see two sets of numbers. The first set is the size of the motor/rotor (the first two represent the diameter and the second two represent the height) and the second set is the KV rating. KV doesn’t stand for kilovolts like you would think it would; it stands for RPM per volt applied. 
<img src="../img/images/aero/image56.png" class="img-responsive floating-image center">
<br>
So if you have a 2000KV motor and a max supply voltage of 12.6, the motor will have a max RPM of 25,200 (2000*12.6). Examples of the numbers you would find written on a motor: 2206 2100KV; 2212 980KV 
<br>
Propellers are measured by the diameter and the pitch, and are measured in inches. By increasing the propeller size on your setup, you can drastically increase the thrust produced by the motors, but this is not without its downside. Larger propellers draw more current, and the responsiveness of the quadcopter is decreased because they're not spinning as fast as smaller propellers. 

<b> ESC: </b> <br>
<img src="../img/images/aero/image10.png" class="img-responsive floating-image center">

<br>
Electronic Speed Controller is the speed controller for the motor that is measured in amps. These deliver the power to the motor as per instruction from the flight controller. To determine the ESCs, you want to find the max current drawn from the motors, which can be found in the motor datasheet.
<br><br>
<b>Assignment:</b> What if you need to change the direction of rotation of the motor, what changes will you need to make?
<br><br>
<b> Battery: </b> <br>
<img src="../img/images/aero/image6.png" class="img-responsive floating-image center">

High power density LiPo batteries are preferred. But they are also quite delicate in their construction and are very sensitive to overcharging and over-discharging. They can easily puff, making them unusable or even burst into flames. It is not uncommon for it to catch on fire due to improper handling and care, but as long as it is treated well, it can fly for years without having any trouble. When looking for a LiPo battery, you will find three numbers: the C rating, the capacity, and the voltage/number of cells. The capacity is how big the battery is and the C rating is how quickly it can deliver the current. The number of cells is written as ‘S’ so 3S would be 3 cells and 4S would be 4 cells and so on. Each cell has a nominal voltage of 3.7V and a max voltage of 4.2V. The power is delivered through a power distribution board to all motors through the ESCs.
<br><br>
<b>Flight controller: </b> <br>
<img src="../img/images/aero/image43.png" class="img-responsive floating-image center">


The flight controller is the brain of the aircraft. It’s a circuit board with a range of sensors that detect movement of the drone, as well as user commands. Using this data, it then controls the speed of the motors to make the craft move as instructed.
<br> It’s basic function is to manipulate the RPM of the individual motors in response to the user's input in the transmitter. If you tell it to go forward, the flight controller will adjust the RPM of the rear motors to be more than the front motors [as explained above]. 
<br> Nearly all flight controllers have basic sensors such as Gyroscopes and Accelerometer. Some FC include more advanced sensors such as Barometer (barometric pressure sensors) and magnetometer (compass). The FC is also a hub for other peripherals, such as GPS, LED, Sonar sensor etc.
<br><br>
<b> Transmitter & Receiver: </b>
<br>
<img src="../img/images/aero/image54.png" class="img-responsive floating-image center">
<br>
We already saw transmitters and receivers in the RC Plane section. For a multirotor, Receiver is connected to a flight controller. 
<br><br>


You want to make sure your transmitter is reliable and that you can trust it because if your transmitter fails on you while you’re flying, your quadcopter can drop out of the sky and potentially injure or damage something or someone.
<br><br>


<div class="blogPageSubHeading"> Line of Sight</div>
<br><br>
So now we have a drone which can fly. <br>
Let’s fly then? <br>
<img src="../img/images/aero/image41.gif" class="img-responsive floating-image center">

<br>
When flying you will notice that the UAV is limited by your visual line of sight to it. Not that it can’t cover the distance, but because you want to be able to see it, in order to maneuver it. Essentially limiting your range of distance covered. Also as the UAV is very small [in the case above], the farther it gets the harder it becomes to spot.
<br><br>

So what do you do? Well we can try to fly in an open ground with less obstructions.
<br> Or we can switch to FPV, just like in video games.
<br><br>

<div class="blogPageSubHeading">First Person View</div>
<br>
<img src="../img/images/aero/image23.gif" class="img-responsive floating-image center">
<br>
We utilise an FPV camera, installed on the drone. This allows a first person view of the drone while flying. This makes flying through long obstacles easy as there is no limitation to line of sight to the drone.
<br>
<img src="../img/images/aero/image40.png" class="img-responsive floating-image left" width="250px">
<img src="../img/images/aero/image14.png" class="img-responsive floating-image right" width="400px">
<br><br><br><br><br><br><br><br><br>  <br><br>  <center>  FPV cam                                                             &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;     &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;     &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;   &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;   &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;     &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;   &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;   &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;   &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;              Analog feed of the camera</center>    
<br><br>
<img src="../img/images/aero/image21.jpg" class="img-responsive floating-image center">
<br>
An FPV cam utilizes a fisheye view lens which provides a wide angle coverage from the drone which can then be viewed on a portable monitor or fpv goggles. This setup requires its own set of transmitter and receiver and uses an analog feed to deliver the video. 
<br> But..
<br> Did you notice the quadcopter moves forward by using its rear motors at a higher thrust, which lifts the rear of the quad. Well then if we mount the camera straight on the frame we can only see the ground.  
<br> So, that’s why fpv drones have their camera(s) mounted at an angle such that when moving forward, the camera view is aligned with the horizontal.
<br><br>
<img src="../img/images/aero/image18.jpg" class="img-responsive floating-image center">

<center> A freestyle drone has 2 camera mounts. Notice both of them are inclined.</center>
<br>
<br><br>
Here’s a little infographic to sum up this topic: <br>
<img src="../img/images/aero/image37.png" class="img-responsive floating-image center">
<br>
Hyped up yet? Want to make your own? <br>
Do it! Let us know if you have any doubts in the process.
<br>
<a href="mailto:harshit@zine.co.in">harshit@zine.co.in</a> <br>
<a href="mailto:chirayu@zine.co.in">chirayu@zine.co.in</a>
<br><br><br>
        <br><br>
        <ul class="pager">
            <li class="previous"><a href="./memory.php">Previous</a></li>

            <li class="next"><a href="./pseudo.php">Next</a></li>
        </ul>



    </div>
</div>

<?php include('footer-1.php') ?>

</html>